const wordOptions = [
  "Pulp Fiction",
  "The Manchurian Candidate",
  "Taxi Driver",
  "The Man Who Shot Liberty Valance",
  "Forty Five Years",
  "Dunkirk",
  "Before Midnight",
  "WALL-E",
  "Faces Places",
  "A Separation",
  "Zero Dark Thirty",
  "Snow White and the Seven Dwarfs",
  "Double Idemnity",
  "I Am Not Your Negro",
  "The Social Network",
  "The Grapes of Wrath",
  "Toy Story",
  "Carol",
  "Beauty and the Beast",
  "Spirited Away",
  "Gravity",
  "Mean Streets",
  "A Streetcar Named Desire",
  "Ratatouille",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "The Maltese Falcon",
  "Rosemary's Baby",
  "Manchester by the Sea",
  "Twelve Angry Men",
  "Twelve Years a Slave",
  "Ran",
  "American Graffiti",
  "Psycho",
  "Some Like It Hot",
  "Four Months, Three Weeks and Two Days",
  "Gone With The Wind",
  "My Left Foot",
  "Hoop Dreams",
  "All About Eve",
  "North by Northwest",
  "Pan's Labyrinth",
  "Moonlight",
  "The Treasure of the Sierra Madre",
  "Singin' In The Rain",
  "Three Colors: Red",
  "Boyhood",
  "Casablanca",
  "Rear Window",
  "The Godfather",
  "Citizen Kane"
];

module.exports = wordOptions;
